AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3]
BATCH_SIZE: 16
EPOCHS: 2
INCLUDE_TOP: False
CLASSES: 2
WEIGHTS: imagenet
LEARNING_RATE: 0.01

# AUGMENTATION: True
# IMAGE_SIZE: [224, 224, 3]
# BATCH_SIZE: 32
# EPOCHS: 5
# INCLUDE_TOP: False
# CLASSES: 2
# WEIGHTS: imagenet
# LEARNING_RATE: 0.001

# AUGMENTATION: False
# IMAGE_SIZE: [224, 224, 3]
# BATCH_SIZE: 32
# EPOCHS: 5
# INCLUDE_TOP: False
# CLASSES: 2
# WEIGHTS: imagenet
# LEARNING_RATE: 0.001